import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from '@/components/navigation'
import Activity from "@/components/activity";
import Navigate from "@/components/navigate";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative max-w-9xl flex-1 h-screen w-screen flex flex-col">{children}
        <Navigation/>
        <Activity/>
         <Toaster
          position="top-right"
          toastOptions={{
            style: {
              borderRadius: "10px",
              background: "#333",
              color: "#fff",
            },
          }}
        />
        <Navigate/>
      </body>
    </html>
  );
}
